# vim: set tabstop=2 shiftwidth=2 expandtab:
language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/composer/.cache

before_install:
    - travis/scripts/install-extension.sh

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
