# vim: set tabstop=2 shiftwidth=2 expandtab:
language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/composer/.cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
