# vim: set tabstop=2 shiftwidth=2 expandtab:
language: php

php:
  - 5.4
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/composer/.cache

install:
  - composer install --prefer-dist --no-interaction

before_script: phpenv config-add travis/etc/php-mongo.ini

script:
  - vendor/bin/phpunit

