# vim: set tabstop=2 shiftwidth=2 expandtab:
language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/composer/.cache

before_install:
    - phpenv config-add travis/etc/php-mongo.ini
    - pecl install mongodb
    - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
