# vim: set tabstop=2 shiftwidth=2 expandtab:
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/composer/.cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpunit
